### ISSUE TITLE
Empty output file error

### ISSUE THREAD

**Issue by PhilPalmer** [solonas13/REAL#3]
Hi, I tried running the following command:
```bash
time real -p SRR346617.fq -t ITAG2_genomic.fasta -o output.sam
```

And this is the output:
```
This is real version 0.0.31
real is distributed under version 3.0 of the GNU GENERAL PUBLIC LICENSE.
Machine supports popcnt instruction.
fraction of memory used will be 0.75
detected 122951 mega bytes of physical memory, of which we will use 92213(96693033984)
pattern file is FASTQ rewrite is on
filter_mult=0.0714286
Rewriting pattern file to temporary file tempfile.IzNOmP
5485868                            
Concatenating temporary files...done.
Starting matching for unique best hits using 16 matching threads.
Pattern length 35 acgtcodelength=9 acgtncodelength=18
idbase=0 idnbase=5480349 patlen=35 patpos=12 patid=241135376 patnum=5480349 patnpos=542383133 patnid=542675648 patnnum=5519

Pattern length 35 acgtcodelength=9 acgtncodelength=18
idbase=0 idnbase=5480349 patlen=35 patpos=12 patid=241135376 patnum=5480349 patnpos=542383133 patnid=542675648 patnnum=5519

Pattern length 35 acgtcodelength=9 acgtncodelength=18
idbase=0 idnbase=5480349 patlen=35 patpos=12 patid=241135376 patnum=5480349 patnpos=542383133 patnid=542675648 patnnum=5519

unique: 0

real	0m28.845s
user	0m23.460s
sys	0m18.928s
```

The command seems to run but the output file is empty.

Do you know what causes this? Is it a memory error? 
The size of the files are as follows:
```
758M ITAG2_genomic.fasta
675M SRR346617.fq
0 output.sam
```

This was run on a r3.4xlarge instance which has 16 CPUs and 122GiB of memory

Any help would be much appreciated, thanks in advance

**Comment by solonas13** [comment]
Hi there,

Please try to rename your input file to .fa not .fasta, and let me know if this works.

Best, Solon.

**Comment by PhilPalmer** [comment]
Thanks for your quick reply, it's running now. I'll let you know if I have any more issues

**Comment by PhilPalmer** [comment]
It worked 😃 
What are the memory requirements for the tool? Is it dependent on the file size/number fo cores? Can you limit the amount of memory?

**Comment by solonas13** [comment]
Hi, thanks. For the memory you can use

-f <fraction of physical memory to use, default=0.75>

The more memory you use the faster the tool gets.

Best, Solon.

**Comment by PhilPalmer** [comment]
Do you know how long it will take for a 1GB FASTQ?
Or a 10GB FASTQ?
(With default of `-f 0.75`)

Also what is the best number of CPUs to use eg 12/24/36? Does it scale linearly?

**Comment by solonas13** [comment]
Everything depends on **how big the reference is** as well. For sure I cannot give an estimation. This benchmark could give an estimation: https://nms.kcl.ac.uk/informatics/projects/real/?id=ben

Only the read matching part scales linearly. Not the indexing part. The more CPUs the better for the matching. For indexing it will not speed up.
